# -*- coding: utf-8 -*-
"""Content to Content.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rQJn01t_YodyI2BueJEn6QgkJE6JpFTu
"""

!pip install openpyxl pandas -q

import openpyxl
import pandas as pd
import re
import glob
import warnings
from google.colab import files

warnings.filterwarnings('ignore', category=UserWarning, module='openpyxl')

# 1. SMART HEADER TRANSLATOR (Now catches plurals like "Patterns")
def map_attribute_header(raw_attr):
    raw = str(raw_attr).lower().strip()
    if 'display' in raw or 'title' in raw: return 'productdisplayname'
    if 'list view' in raw: return 'listviewname'
    if 'product detail' in raw: return 'productdetails'
    if 'size' in raw and 'fit' in raw: return 'sizeandfitdescription'
    if 'material' in raw and 'care' in raw: return 'materialcaredescription'
    if 'colour' in raw or 'color' in raw: return 'colour'

    # Catch common seller misnomers
    if raw == 'patterns': return 'pattern'
    if raw == 'fashion trends': return 'maintrend'

    return re.sub(r'[^a-z0-9]', '', raw)

def clean_id(val):
    try: return str(int(float(str(val).strip())))
    except: return str(val).strip()

def normalize_col(name):
    name = str(name).strip().lower()
    return re.sub(r'[^a-z0-9]', '', name)

print("🔍 Initializing CatVibe Smart Seller Mapping (Multi-Row Edition)...")

all_xlsx = glob.glob("*.xlsx")
seller_candidates = []
template_candidates = []

# Auto-Detect which file is the Target and which is the Source
for f in all_xlsx:
    if f.startswith("Output_") or f.startswith("Smart_"): continue
    try:
        xls = pd.ExcelFile(f)
        if 'masterdata' in xls.sheet_names:
            template_candidates.append(f)
        else:
            df_peek = pd.read_excel(xls, sheet_name=xls.sheet_names[0], nrows=1)
            if 'myntraHSN' in df_peek.columns or 'vendorArticleName' in df_peek.columns:
                template_candidates.append(f)
            else:
                seller_candidates.append(f)
    except: pass

if not template_candidates:
    print("❌ Error: Could not detect the Myntra Catalog Template.")
else:
    template_file = template_candidates[0]
    output_file = f"Output_Fixed_{template_file.replace('Fixed_', '')}"
    print(f"🎯 Target Template: {template_file}")

    master_style_dict = {}

    # 2. AGGREGATE & PARSE SELLER FILES
    print(f"\n📚 Scanning {len(seller_candidates)} Seller files...")

    for filepath in seller_candidates:
        try:
            xls = pd.ExcelFile(filepath)
            sheet_name = 'Style Sheet' if 'Style Sheet' in xls.sheet_names else ('Styles' if 'Styles' in xls.sheet_names else xls.sheet_names[0])
            df = pd.read_excel(filepath, sheet_name=sheet_name, header=None)

            h_row = 0 if 'field names' in str(df.iloc[0].values).lower() else 2
            sh_row = h_row + 1
            start_row = sh_row + 1

            headers = df.iloc[h_row].fillna(method='ffill').tolist()
            sub_headers = df.iloc[sh_row].fillna('').tolist()

            combined_cols = []
            for i, (h, sh) in enumerate(zip(headers, sub_headers)):
                if i == 0:
                    combined_cols.append('style_id')
                    continue
                h_str = str(h).strip().lower().replace('\n', ' ') if pd.notna(h) else ''
                sh_str = str(sh).strip().lower().replace('\n', ' ')
                if 'correct' in sh_str or 'new' in sh_str: combined_cols.append(f"{h_str}_new")
                else: combined_cols.append(f"{h_str}_{sh_str}")

            df_data = df.iloc[start_row:].copy()
            df_data.columns = combined_cols

            # 🛡️ THE FIX: Forward-Fill the Style ID to catch empty rows beneath it
            df_data['style_id'] = df_data['style_id'].fillna(method='ffill')

            cols_to_keep = ['style_id'] + [c for c in combined_cols if c.endswith('_new') or 'attribute' in c]
            df_clean = df_data[cols_to_keep].dropna(subset=['style_id']).copy()

            attr_key_col = next((c for c in df_clean.columns if c.startswith('attribute') and not c.endswith('new') and not c.endswith('inputs')), None)
            attr_val_col = next((c for c in df_clean.columns if c.startswith('attribute') and c.endswith('new')), None)
            spec_col = next((c for c in df_clean.columns if 'specification_new' in c), None)

            for _, row in df_clean.iterrows():
                sid = clean_id(row['style_id'])
                if sid not in master_style_dict: master_style_dict[sid] = {}

                # A. Handle Multiline Single-Cell Attributes
                if attr_key_col and spec_col and pd.notna(row[attr_key_col]) and pd.notna(row[spec_col]) and '\n' in str(row[attr_key_col]):
                    attrs = str(row[attr_key_col]).split('\n')
                    vals = str(row[spec_col]).split('\n')
                    for i in range(min(len(attrs), len(vals))):
                        key = map_attribute_header(attrs[i])
                        val = vals[i].strip()
                        if key and val and val.lower() != 'nan':
                            master_style_dict[sid][key] = val

                # B. Handle Multi-Row Attributes (The Bewakoof Format)
                elif attr_key_col and attr_val_col and pd.notna(row[attr_key_col]) and pd.notna(row[attr_val_col]):
                    k = str(row[attr_key_col]).strip()
                    v = str(row[attr_val_col]).strip()
                    if k.lower() != 'nan' and v.lower() != 'nan':
                        master_style_dict[sid][map_attribute_header(k)] = v

                # C. Handle Standard Free-Text Columns
                for col in df_clean.columns:
                    if col.endswith('_new') and col != spec_col and not col.startswith('attribute'):
                        if pd.notna(row[col]) and str(row[col]).strip().lower() != 'nan':
                            key = map_attribute_header(col.replace('_new', ''))
                            master_style_dict[sid][key] = str(row[col]).strip()

            print(f"  -> ✅ Parsed data from {filepath}")
        except Exception as e:
            print(f"  -> ⚠️ Failed to parse {filepath}: {e}")

    print(f"\n✅ Ready to inject updates for {len(master_style_dict)} unique styles.")

    # 3. INJECT INTO MYNTRA TEMPLATE WITH SMART BRAND INJECTOR
    print(f"\n⏳ Updating Myntra Template: {template_file}...")
    wb = openpyxl.load_workbook(template_file)
    mapped_count = 0
    brand_injection_count = 0
    updated_locations = {}

    for sheet_name in wb.sheetnames:
        if sheet_name == 'masterdata': continue
        ws = wb[sheet_name]

        col_map = {normalize_col(cell.value): idx for idx, cell in enumerate(ws[1], 1) if cell.value}
        target_style_col = col_map.get('styleid')
        brand_col_idx = col_map.get('brand')

        if target_style_col:
            for row in range(2, ws.max_row + 1):
                raw_sid = ws.cell(row=row, column=target_style_col).value
                if not raw_sid: continue
                sid = clean_id(raw_sid)

                if sid in master_style_dict:
                    source_data = master_style_dict[sid]
                    for mapped_attr, val in source_data.items():
                        if mapped_attr in col_map:

                            final_val = str(val).strip()

                            # Auto-Brand Injector
                            if mapped_attr == 'productdisplayname' and brand_col_idx:
                                target_brand = str(ws.cell(row=row, column=brand_col_idx).value).strip()
                                if target_brand and target_brand.lower() not in ['none', 'nan', '']:
                                    if target_brand.lower() not in final_val.lower():
                                        final_val = f"{target_brand} {final_val}"
                                        brand_injection_count += 1

                            ws.cell(row=row, column=col_map[mapped_attr]).value = final_val
                            mapped_count += 1

                            if sheet_name not in updated_locations: updated_locations[sheet_name] = set()
                            orig_col_name = next((c.value for c in ws[1] if normalize_col(c.value) == mapped_attr), mapped_attr)
                            updated_locations[sheet_name].add(str(orig_col_name))

    print(f"\n🚀 SUCCESS! {mapped_count} attributes mapped to the template.")
    if brand_injection_count > 0:
        print(f"🛡️ Auto-injected missing Brand Name into {brand_injection_count} display titles.")

    if updated_locations:
        print("\n📍 WHERE TO LOOK IN YOUR EXCEL FILE:")
        for sh, cols in updated_locations.items():
            print(f"   - Sheet: [{sh}] -> Updated Columns: {list(cols)}")

    print(f"\n💾 Saving: {output_file}")
    wb.save(output_file)
    try:
        files.download(output_file)
    except:
        print("  -> Download blocked by browser. File available in the left panel.")



"""[link text](https://)"""